[package]
name = "festivus"
version = "0.1.0"
authors = ["Michael Sproul <micsproul@gmail.com>"]

[dependencies]

iron = "*"
r2d2 = "*"
r2d2_postgres = "*"
chrono = "0.2"
postgres = "*"

[dependencies.iron-postgres-middleware]
git = "https://github.com/martinsp/iron-postgres-middleware.git"
